// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const ACPShareRegistryArtifact = {
  contractName: 'ACPShareRegistry',
  isFixed: false,
  abi: [
    {
      type: 'function',
      name: 'getShare',
      inputs: [
        {
          name: 'shareId',
          type: 'bytes32',
          internalType: 'bytes32',
        },
      ],
      outputs: [
        {
          name: '',
          type: 'tuple',
          internalType: 'struct ACP',
          components: [
            {
              name: 'issuer',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'expiration',
              type: 'uint64',
              internalType: 'uint64',
            },
            {
              name: 'recipient',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'revokerData',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'revokerContract',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'scope',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'contracts',
              type: 'address[]',
              internalType: 'address[]',
            },
            {
              name: 'handles',
              type: 'bytes32[]',
              internalType: 'bytes32[]',
            },
            {
              name: 'sealingKey',
              type: 'bytes32',
              internalType: 'bytes32',
            },
            {
              name: 'issuerSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
            {
              name: 'recipientSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'isShareValid',
      inputs: [
        {
          name: 'shareId',
          type: 'bytes32',
          internalType: 'bytes32',
        },
      ],
      outputs: [
        {
          name: '',
          type: 'bool',
          internalType: 'bool',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'removeShare',
      inputs: [
        {
          name: 'shareId',
          type: 'bytes32',
          internalType: 'bytes32',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'share',
      inputs: [
        {
          name: 'acp',
          type: 'tuple',
          internalType: 'struct ACP',
          components: [
            {
              name: 'issuer',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'expiration',
              type: 'uint64',
              internalType: 'uint64',
            },
            {
              name: 'recipient',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'revokerData',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'revokerContract',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'scope',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'contracts',
              type: 'address[]',
              internalType: 'address[]',
            },
            {
              name: 'handles',
              type: 'bytes32[]',
              internalType: 'bytes32[]',
            },
            {
              name: 'sealingKey',
              type: 'bytes32',
              internalType: 'bytes32',
            },
            {
              name: 'issuerSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
            {
              name: 'recipientSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      outputs: [
        {
          name: 'shareId',
          type: 'bytes32',
          internalType: 'bytes32',
        },
      ],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'sharesFor',
      inputs: [
        {
          name: 'recipient',
          type: 'address',
          internalType: 'address',
        },
      ],
      outputs: [
        {
          name: 'acps',
          type: 'tuple[]',
          internalType: 'struct ACP[]',
          components: [
            {
              name: 'issuer',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'expiration',
              type: 'uint64',
              internalType: 'uint64',
            },
            {
              name: 'recipient',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'revokerData',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'revokerContract',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'scope',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'contracts',
              type: 'address[]',
              internalType: 'address[]',
            },
            {
              name: 'handles',
              type: 'bytes32[]',
              internalType: 'bytes32[]',
            },
            {
              name: 'sealingKey',
              type: 'bytes32',
              internalType: 'bytes32',
            },
            {
              name: 'issuerSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
            {
              name: 'recipientSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'event',
      name: 'ShareRemoved',
      inputs: [
        {
          name: 'recipient',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        {
          name: 'issuer',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        {
          name: 'shareId',
          type: 'bytes32',
          indexed: false,
          internalType: 'bytes32',
        },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'Shared',
      inputs: [
        {
          name: 'recipient',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        {
          name: 'issuer',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        {
          name: 'shareId',
          type: 'bytes32',
          indexed: false,
          internalType: 'bytes32',
        },
      ],
      anonymous: false,
    },
    {
      type: 'error',
      name: 'AlreadyShared',
      inputs: [],
    },
    {
      type: 'error',
      name: 'IssuerSignatureMissing',
      inputs: [],
    },
    {
      type: 'error',
      name: 'NotIssuer',
      inputs: [],
    },
    {
      type: 'error',
      name: 'NotIssuerOrRecipient',
      inputs: [],
    },
    {
      type: 'error',
      name: 'RecipientMissing',
      inputs: [],
    },
    {
      type: 'error',
      name: 'SealingKeyMustBeEmpty',
      inputs: [],
    },
    {
      type: 'error',
      name: 'ShareExpired',
      inputs: [],
    },
    {
      type: 'error',
      name: 'UnknownShare',
      inputs: [],
    },
  ],
} as const satisfies MockArtifact;
