// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const ACPTimestampRevokerArtifact = {
  contractName: 'ACPTimestampRevoker',
  isFixed: false,
  abi: [
    {
      type: 'function',
      name: 'disabled',
      inputs: [
        {
          name: 'issuer',
          type: 'address',
          internalType: 'address',
        },
        {
          name: 'id',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      outputs: [
        {
          name: '',
          type: 'bool',
          internalType: 'bool',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'revokeAllAt',
      inputs: [
        {
          name: '',
          type: 'address',
          internalType: 'address',
        },
      ],
      outputs: [
        {
          name: '',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'revokeAllExisting',
      inputs: [],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'revokeSingle',
      inputs: [
        {
          name: 'id',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'revokedSingle',
      inputs: [
        {
          name: '',
          type: 'address',
          internalType: 'address',
        },
        {
          name: '',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      outputs: [
        {
          name: '',
          type: 'bool',
          internalType: 'bool',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'event',
      name: 'RevokedAll',
      inputs: [
        {
          name: 'issuer',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        {
          name: 'at',
          type: 'uint256',
          indexed: false,
          internalType: 'uint256',
        },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'RevokedSingle',
      inputs: [
        {
          name: 'issuer',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        {
          name: 'id',
          type: 'uint256',
          indexed: true,
          internalType: 'uint256',
        },
      ],
      anonymous: false,
    },
  ],
} as const satisfies MockArtifact;
