// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const MockCoFHEAddressBookArtifact = {
  contractName: 'MockCoFHEAddressBook',
  isFixed: true,
  fixedAddress: '0xC0F4e00E531a2B086492Ae3DCC1515038307196b',
  abi: [
    {
      type: 'function',
      name: 'exists',
      inputs: [],
      outputs: [
        {
          name: '',
          type: 'bool',
          internalType: 'bool',
        },
      ],
      stateMutability: 'pure',
    },
    {
      type: 'function',
      name: 'getTm',
      inputs: [
        {
          name: 'id',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      outputs: [
        {
          name: 'tm',
          type: 'address',
          internalType: 'address',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'setTm',
      inputs: [
        {
          name: 'id',
          type: 'uint256',
          internalType: 'uint256',
        },
        {
          name: 'tm',
          type: 'address',
          internalType: 'address',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'unsetTm',
      inputs: [
        {
          name: 'id',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'event',
      name: 'TaskManagerSet',
      inputs: [
        {
          name: 'id',
          type: 'uint256',
          indexed: true,
          internalType: 'uint256',
        },
        {
          name: 'previous',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        {
          name: 'current',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
      ],
      anonymous: false,
    },
    {
      type: 'error',
      name: 'InvalidAddress',
      inputs: [],
    },
    {
      type: 'error',
      name: 'TaskManagerNotSet',
      inputs: [
        {
          name: 'id',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
    },
  ],
} as const satisfies MockArtifact;
