// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const MockERC1967ProxyArtifact = {
  contractName: 'MockERC1967Proxy',
  isFixed: false,
  abi: [
    {
      type: 'constructor',
      inputs: [
        {
          name: 'implementation',
          type: 'address',
          internalType: 'address',
        },
        {
          name: 'data',
          type: 'bytes',
          internalType: 'bytes',
        },
      ],
      stateMutability: 'payable',
    },
    {
      type: 'fallback',
      stateMutability: 'payable',
    },
    {
      type: 'event',
      name: 'Upgraded',
      inputs: [
        {
          name: 'implementation',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
      ],
      anonymous: false,
    },
    {
      type: 'error',
      name: 'AddressEmptyCode',
      inputs: [
        {
          name: 'target',
          type: 'address',
          internalType: 'address',
        },
      ],
    },
    {
      type: 'error',
      name: 'ERC1967InvalidImplementation',
      inputs: [
        {
          name: 'implementation',
          type: 'address',
          internalType: 'address',
        },
      ],
    },
    {
      type: 'error',
      name: 'ERC1967NonPayable',
      inputs: [],
    },
    {
      type: 'error',
      name: 'FailedCall',
      inputs: [],
    },
  ],
} as const satisfies MockArtifact;
