// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const MockACPArtifact = {
  contractName: 'MockACP',
  isFixed: false,
  abi: [
    {
      type: 'constructor',
      inputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'checkPermissionValidity',
      inputs: [
        {
          name: 'permission',
          type: 'tuple',
          internalType: 'struct ACP',
          components: [
            {
              name: 'issuer',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'expiration',
              type: 'uint64',
              internalType: 'uint64',
            },
            {
              name: 'recipient',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'validatorId',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'validatorContract',
              type: 'address',
              internalType: 'address',
            },
            {
              name: 'global',
              type: 'bool',
              internalType: 'bool',
            },
            {
              name: 'contracts',
              type: 'address[]',
              internalType: 'address[]',
            },
            {
              name: 'handles',
              type: 'uint256[]',
              internalType: 'uint256[]',
            },
            {
              name: 'sealingKey',
              type: 'bytes32',
              internalType: 'bytes32',
            },
            {
              name: 'issuerSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
            {
              name: 'recipientSignature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      outputs: [
        {
          name: '',
          type: 'bool',
          internalType: 'bool',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'eip712Domain',
      inputs: [],
      outputs: [
        {
          name: 'fields',
          type: 'bytes1',
          internalType: 'bytes1',
        },
        {
          name: 'name',
          type: 'string',
          internalType: 'string',
        },
        {
          name: 'version',
          type: 'string',
          internalType: 'string',
        },
        {
          name: 'chainId',
          type: 'uint256',
          internalType: 'uint256',
        },
        {
          name: 'verifyingContract',
          type: 'address',
          internalType: 'address',
        },
        {
          name: 'salt',
          type: 'bytes32',
          internalType: 'bytes32',
        },
        {
          name: 'extensions',
          type: 'uint256[]',
          internalType: 'uint256[]',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'hashTypedDataV4',
      inputs: [
        {
          name: 'structHash',
          type: 'bytes32',
          internalType: 'bytes32',
        },
      ],
      outputs: [
        {
          name: '',
          type: 'bytes32',
          internalType: 'bytes32',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'event',
      name: 'EIP712DomainChanged',
      inputs: [],
      anonymous: false,
    },
    {
      type: 'error',
      name: 'InvalidShortString',
      inputs: [],
    },
    {
      type: 'error',
      name: 'PermissionInvalid_Disabled',
      inputs: [],
    },
    {
      type: 'error',
      name: 'PermissionInvalid_Expired',
      inputs: [],
    },
    {
      type: 'error',
      name: 'PermissionInvalid_IssuerSignature',
      inputs: [],
    },
    {
      type: 'error',
      name: 'PermissionInvalid_RecipientSignature',
      inputs: [],
    },
    {
      type: 'error',
      name: 'StringTooLong',
      inputs: [
        {
          name: 'str',
          type: 'string',
          internalType: 'string',
        },
      ],
    },
  ],
} as const satisfies MockArtifact;
