// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const TestBedArtifact = {
  contractName: 'TestBed',
  isFixed: true,
  fixedAddress: '0x0000000000000000000000000000000000005003',
  abi: [
    {
      type: 'function',
      name: 'add',
      inputs: [
        {
          name: 'inNumber',
          type: 'tuple',
          internalType: 'struct InEuint32',
          components: [
            {
              name: 'ctHash',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'securityZone',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'utype',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'signature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'decrypt',
      inputs: [],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'eNumber',
      inputs: [],
      outputs: [
        {
          name: '',
          type: 'bytes32',
          internalType: 'euint32',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'exists',
      inputs: [],
      outputs: [
        {
          name: '',
          type: 'bool',
          internalType: 'bool',
        },
      ],
      stateMutability: 'pure',
    },
    {
      type: 'function',
      name: 'getDecryptResult',
      inputs: [
        {
          name: 'input1',
          type: 'bytes32',
          internalType: 'euint32',
        },
      ],
      outputs: [
        {
          name: '',
          type: 'uint32',
          internalType: 'uint32',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'getDecryptResultSafe',
      inputs: [
        {
          name: 'input1',
          type: 'bytes32',
          internalType: 'euint32',
        },
      ],
      outputs: [
        {
          name: 'value',
          type: 'uint32',
          internalType: 'uint32',
        },
        {
          name: 'decrypted',
          type: 'bool',
          internalType: 'bool',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'increment',
      inputs: [],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'mul',
      inputs: [
        {
          name: 'inNumber',
          type: 'tuple',
          internalType: 'struct InEuint32',
          components: [
            {
              name: 'ctHash',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'securityZone',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'utype',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'signature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'numberHash',
      inputs: [],
      outputs: [
        {
          name: '',
          type: 'bytes32',
          internalType: 'bytes32',
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'publishDecryptResult',
      inputs: [
        {
          name: 'input',
          type: 'bytes32',
          internalType: 'euint32',
        },
        {
          name: 'result',
          type: 'uint32',
          internalType: 'uint32',
        },
        {
          name: 'signature',
          type: 'bytes',
          internalType: 'bytes',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'setNumber',
      inputs: [
        {
          name: 'inNumber',
          type: 'tuple',
          internalType: 'struct InEuint32',
          components: [
            {
              name: 'ctHash',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'securityZone',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'utype',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'signature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'setNumberTrivial',
      inputs: [
        {
          name: 'inNumber',
          type: 'uint32',
          internalType: 'uint32',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'sub',
      inputs: [
        {
          name: 'inNumber',
          type: 'tuple',
          internalType: 'struct InEuint32',
          components: [
            {
              name: 'ctHash',
              type: 'uint256',
              internalType: 'uint256',
            },
            {
              name: 'securityZone',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'utype',
              type: 'uint8',
              internalType: 'uint8',
            },
            {
              name: 'signature',
              type: 'bytes',
              internalType: 'bytes',
            },
          ],
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'error',
      name: 'InvalidEncryptedInput',
      inputs: [
        {
          name: 'got',
          type: 'uint8',
          internalType: 'uint8',
        },
        {
          name: 'expected',
          type: 'uint8',
          internalType: 'uint8',
        },
      ],
    },
    {
      type: 'error',
      name: 'SecurityZoneOutOfBounds',
      inputs: [
        {
          name: 'value',
          type: 'int32',
          internalType: 'int32',
        },
      ],
    },
  ],
} as const satisfies MockArtifact;
