import { execSync } from 'child_process';
import * as fs from 'fs';
import {
  TASK_MANAGER_ADDRESS,
  MOCKS_ZK_VERIFIER_ADDRESS,
  MOCKS_QUERY_DECRYPTER_ADDRESS,
  TEST_BED_ADDRESS,
} from '@cofhe/sdk';

const fixedContracts = {
  MockTaskManager: TASK_MANAGER_ADDRESS,
  MockZkVerifier: MOCKS_ZK_VERIFIER_ADDRESS,
  MockQueryDecrypter: MOCKS_QUERY_DECRYPTER_ADDRESS,
  TestBed: TEST_BED_ADDRESS,
};

const nonFixedContracts = {
  MockACL: true,
};

function inspect(contract: string, field: string): any {
  const cmd = `forge inspect ${contract} ${field} --json`;
  const out = execSync(cmd, { encoding: 'utf8' }).trim();

  if (field === 'bytecode' || field === 'deployedBytecode') {
    // Both are emitted as quoted strings (JSON-encoded)
    return out.toLowerCase();
  }

  // ABI and metadata are full JSON
  return JSON.parse(out);
}

// Build fixed contracts

for (const [name, fixedAddress] of Object.entries(fixedContracts)) {
  const abi = inspect(name, 'abi');
  const deployedBytecode = inspect(name, 'deployedBytecode');

  const artifact = {
    contractName: name,
    isFixed: true,
    fixedAddress,
    abi,
    deployedBytecode,
  };

  fs.writeFileSync(
    `src/${name}.ts`,
    `// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const ${name}Artifact = ${JSON.stringify(artifact, null, 2)} satisfies MockArtifact;`
  );
}

// Build non-fixed contracts

for (const [name] of Object.entries(nonFixedContracts)) {
  const abi = inspect(name, 'abi');
  const bytecode = inspect(name, 'bytecode');

  const artifact = {
    contractName: name,
    isFixed: false,
    abi,
    bytecode,
  };

  fs.writeFileSync(
    `src/${name}.ts`,
    `// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const ${name}Artifact = ${JSON.stringify(artifact, null, 2)} satisfies MockArtifact;`
  );
}
