import { execSync } from 'child_process';
import * as fs from 'fs';
import {
  TASK_MANAGER_ADDRESS,
  MOCKS_ZK_VERIFIER_ADDRESS,
  MOCKS_THRESHOLD_NETWORK_ADDRESS,
} from '@cofhe/sdk';

const fixedContracts = {
  MockTaskManager: {
    fixedAddress: TASK_MANAGER_ADDRESS,
    inspectTarget: 'MockTaskManager',
  },
  MockZkVerifier: {
    fixedAddress: MOCKS_ZK_VERIFIER_ADDRESS,
    inspectTarget: 'MockZkVerifier',
  },
  MockThresholdNetwork: {
    fixedAddress: MOCKS_THRESHOLD_NETWORK_ADDRESS,
    inspectTarget: 'MockThresholdNetwork',
  },
};

const nonFixedContracts = {
  MockACL: {
    inspectTarget: 'MockACL',
  },
  SimpleTest: {
    inspectTarget: 'contracts/SimpleTest.sol:SimpleTest',
  },
};

function inspect(contract: string, field: string): any {
  const cmd = `forge inspect ${contract} ${field} --json`;
  const out = execSync(cmd, { encoding: 'utf8' }).trim();
  return JSON.parse(out);
}

const abiDir = 'abi';
fs.mkdirSync(abiDir, { recursive: true });

// Build fixed contracts

for (const [name, { fixedAddress, inspectTarget }] of Object.entries(fixedContracts)) {
  const abi = inspect(inspectTarget, 'abi');

  const artifact = {
    contractName: name,
    isFixed: true,
    fixedAddress,
    abi,
  };

  fs.writeFileSync(
    `src/${name}.ts`,
    `// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const ${name}Artifact = ${JSON.stringify(artifact, null, 2)} as const satisfies MockArtifact;`
  );

  fs.writeFileSync(`${abiDir}/${name}.json`, JSON.stringify(abi, null, 2));
}

// Build non-fixed contracts

for (const [name, { inspectTarget }] of Object.entries(nonFixedContracts)) {
  const abi = inspect(inspectTarget, 'abi');

  const artifact = {
    contractName: name,
    isFixed: false,
    abi,
  };

  fs.writeFileSync(
    `src/${name}.ts`,
    `// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const ${name}Artifact = ${JSON.stringify(artifact, null, 2)} as const satisfies MockArtifact;`
  );

  fs.writeFileSync(`${abiDir}/${name}.json`, JSON.stringify(abi, null, 2));
}
