import { execSync } from 'child_process';
import * as fs from 'fs';
import { TASK_MANAGER_ADDRESS, MOCKS_ZK_VERIFIER_ADDRESS, MOCKS_THRESHOLD_NETWORK_ADDRESS } from '@cofhe/sdk';

const contracts: Array<{ name: string; fixedAddress?: string }> = [
  {
    name: 'MockTaskManager',
    fixedAddress: TASK_MANAGER_ADDRESS,
  },
  {
    name: 'MockZkVerifier',
    fixedAddress: MOCKS_ZK_VERIFIER_ADDRESS,
  },
  {
    name: 'MockThresholdNetwork',
    fixedAddress: MOCKS_THRESHOLD_NETWORK_ADDRESS,
  },
  {
    name: 'MockACL',
  },
];

function inspect(contract: string, field: string): any {
  const cmd = `forge inspect ${contract} ${field} --json`;
  const out = execSync(cmd, { encoding: 'utf8' }).trim();
  return JSON.parse(out);
}

const abiDir = 'abi';
fs.mkdirSync(abiDir, { recursive: true });

for (const { name, fixedAddress } of contracts) {
  const abi = inspect(name, 'abi');

  const artifact = fixedAddress
    ? {
      contractName: name,
      isFixed: true,
      fixedAddress,
      abi,
    }
    : {
      contractName: name,
      isFixed: false,
      abi,
    };

  fs.writeFileSync(
    `src/${name}.ts`,
    `// This file is auto-generated by build-artifacts.ts
import { type MockArtifact } from './types';

export const ${name}Artifact = ${JSON.stringify(artifact, null, 2)} as const satisfies MockArtifact;`
  );

  fs.writeFileSync(`${abiDir}/${name}.json`, JSON.stringify(abi, null, 2));
}
