/**
 * Removes typechain-generated factory files and updates the index to export only contract types.
 * Run after typechain in the build pipeline.
 */
import * as fs from 'fs';
import * as path from 'path';

const typechainDir = path.join(process.cwd(), 'src', 'typechain-types');
const indexPath = path.join(typechainDir, 'index.ts');

if (!fs.existsSync(typechainDir)) {
  console.error('typechain-types directory not found');
  process.exit(1);
}

// Remove factories directory
const factoriesDir = path.join(typechainDir, 'factories');
if (fs.existsSync(factoriesDir)) {
  fs.rmSync(factoriesDir, { recursive: true });
}

// Rewrite index.ts to export only contract types (no factories)
const contractFiles = fs.readdirSync(typechainDir).filter((f) => {
  if (f === 'index.ts' || f === 'common.ts') return false;
  return f.endsWith('.ts') && fs.statSync(path.join(typechainDir, f)).isFile();
});

const contractNames = contractFiles.map((f) => path.basename(f, '.ts')).sort();

const indexContent = `/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
${contractNames.map((name) => `export type { ${name} } from './${name}';`).join('\n')}
`;

fs.writeFileSync(indexPath, indexContent);
