/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export type ACPStruct = {
  issuer: AddressLike;
  expiration: BigNumberish;
  recipient: AddressLike;
  revokerData: BigNumberish;
  revokerContract: AddressLike;
  scope: BigNumberish;
  contracts: AddressLike[];
  handles: BytesLike[];
  sealingKey: BytesLike;
  issuerSignature: BytesLike;
  recipientSignature: BytesLike;
};

export type ACPStructOutput = [
  issuer: string,
  expiration: bigint,
  recipient: string,
  revokerData: bigint,
  revokerContract: string,
  scope: bigint,
  contracts: string[],
  handles: string[],
  sealingKey: string,
  issuerSignature: string,
  recipientSignature: string,
] & {
  issuer: string;
  expiration: bigint;
  recipient: string;
  revokerData: bigint;
  revokerContract: string;
  scope: bigint;
  contracts: string[];
  handles: string[];
  sealingKey: string;
  issuerSignature: string;
  recipientSignature: string;
};

export interface ACPShareRegistryInterface extends Interface {
  getFunction(nameOrSignature: 'getShare' | 'isShareValid' | 'removeShare' | 'share' | 'sharesFor'): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: 'ShareRemoved' | 'Shared'): EventFragment;

  encodeFunctionData(functionFragment: 'getShare', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'isShareValid', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'removeShare', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'share', values: [ACPStruct]): string;
  encodeFunctionData(functionFragment: 'sharesFor', values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: 'getShare', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'isShareValid', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'removeShare', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'share', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'sharesFor', data: BytesLike): Result;
}

export namespace ShareRemovedEvent {
  export type InputTuple = [recipient: AddressLike, issuer: AddressLike, shareId: BytesLike];
  export type OutputTuple = [recipient: string, issuer: string, shareId: string];
  export interface OutputObject {
    recipient: string;
    issuer: string;
    shareId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharedEvent {
  export type InputTuple = [recipient: AddressLike, issuer: AddressLike, shareId: BytesLike];
  export type OutputTuple = [recipient: string, issuer: string, shareId: string];
  export interface OutputObject {
    recipient: string;
    issuer: string;
    shareId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ACPShareRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ACPShareRegistry;
  waitForDeployment(): Promise<this>;

  interface: ACPShareRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  getShare: TypedContractMethod<[shareId: BytesLike], [ACPStructOutput], 'view'>;

  isShareValid: TypedContractMethod<[shareId: BytesLike], [boolean], 'view'>;

  removeShare: TypedContractMethod<[shareId: BytesLike], [void], 'nonpayable'>;

  share: TypedContractMethod<[acp: ACPStruct], [string], 'nonpayable'>;

  sharesFor: TypedContractMethod<[recipient: AddressLike], [ACPStructOutput[]], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'getShare'): TypedContractMethod<[shareId: BytesLike], [ACPStructOutput], 'view'>;
  getFunction(nameOrSignature: 'isShareValid'): TypedContractMethod<[shareId: BytesLike], [boolean], 'view'>;
  getFunction(nameOrSignature: 'removeShare'): TypedContractMethod<[shareId: BytesLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'share'): TypedContractMethod<[acp: ACPStruct], [string], 'nonpayable'>;
  getFunction(nameOrSignature: 'sharesFor'): TypedContractMethod<[recipient: AddressLike], [ACPStructOutput[]], 'view'>;

  getEvent(
    key: 'ShareRemoved'
  ): TypedContractEvent<ShareRemovedEvent.InputTuple, ShareRemovedEvent.OutputTuple, ShareRemovedEvent.OutputObject>;
  getEvent(
    key: 'Shared'
  ): TypedContractEvent<SharedEvent.InputTuple, SharedEvent.OutputTuple, SharedEvent.OutputObject>;

  filters: {
    'ShareRemoved(address,address,bytes32)': TypedContractEvent<
      ShareRemovedEvent.InputTuple,
      ShareRemovedEvent.OutputTuple,
      ShareRemovedEvent.OutputObject
    >;
    ShareRemoved: TypedContractEvent<
      ShareRemovedEvent.InputTuple,
      ShareRemovedEvent.OutputTuple,
      ShareRemovedEvent.OutputObject
    >;

    'Shared(address,address,bytes32)': TypedContractEvent<
      SharedEvent.InputTuple,
      SharedEvent.OutputTuple,
      SharedEvent.OutputObject
    >;
    Shared: TypedContractEvent<SharedEvent.InputTuple, SharedEvent.OutputTuple, SharedEvent.OutputObject>;
  };
}
