/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export type ACPStruct = {
  issuer: AddressLike;
  expiration: BigNumberish;
  recipient: AddressLike;
  revokerData: BigNumberish;
  revokerContract: AddressLike;
  scope: BigNumberish;
  contracts: AddressLike[];
  handles: BytesLike[];
  sealingKey: BytesLike;
  issuerSignature: BytesLike;
  recipientSignature: BytesLike;
};

export type ACPStructOutput = [
  issuer: string,
  expiration: bigint,
  recipient: string,
  revokerData: bigint,
  revokerContract: string,
  scope: bigint,
  contracts: string[],
  handles: string[],
  sealingKey: string,
  issuerSignature: string,
  recipientSignature: string,
] & {
  issuer: string;
  expiration: bigint;
  recipient: string;
  revokerData: bigint;
  revokerContract: string;
  scope: bigint;
  contracts: string[];
  handles: string[];
  sealingKey: string;
  issuerSignature: string;
  recipientSignature: string;
};

export interface MockThresholdNetworkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'decodeLowLevelReversion'
      | 'decryptForTxWithACP'
      | 'decryptForTxWithoutACP'
      | 'exists'
      | 'initialize'
      | 'mockAcl'
      | 'mockQueryDecrypt'
      | 'mockTaskManager'
      | 'queryDecrypt'
      | 'querySealOutput'
      | 'seal'
      | 'unseal'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'decodeLowLevelReversion', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'decryptForTxWithACP', values: [BigNumberish, ACPStruct]): string;
  encodeFunctionData(functionFragment: 'decryptForTxWithoutACP', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'exists', values?: undefined): string;
  encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike]): string;
  encodeFunctionData(functionFragment: 'mockAcl', values?: undefined): string;
  encodeFunctionData(functionFragment: 'mockQueryDecrypt', values: [BigNumberish, BigNumberish, AddressLike]): string;
  encodeFunctionData(functionFragment: 'mockTaskManager', values?: undefined): string;
  encodeFunctionData(functionFragment: 'queryDecrypt', values: [BigNumberish, BigNumberish, ACPStruct]): string;
  encodeFunctionData(functionFragment: 'querySealOutput', values: [BigNumberish, BigNumberish, ACPStruct]): string;
  encodeFunctionData(functionFragment: 'seal', values: [BigNumberish, BytesLike]): string;
  encodeFunctionData(functionFragment: 'unseal', values: [BytesLike, BytesLike]): string;

  decodeFunctionResult(functionFragment: 'decodeLowLevelReversion', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'decryptForTxWithACP', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'decryptForTxWithoutACP', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mockAcl', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mockQueryDecrypt', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mockTaskManager', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'queryDecrypt', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'querySealOutput', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'seal', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unseal', data: BytesLike): Result;
}

export interface MockThresholdNetwork extends BaseContract {
  connect(runner?: ContractRunner | null): MockThresholdNetwork;
  waitForDeployment(): Promise<this>;

  interface: MockThresholdNetworkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  decodeLowLevelReversion: TypedContractMethod<[data: BytesLike], [string], 'view'>;

  decryptForTxWithACP: TypedContractMethod<
    [ctHash: BigNumberish, acp: ACPStruct],
    [
      [boolean, string, bigint] & {
        allowed: boolean;
        error: string;
        decryptedValue: bigint;
      },
    ],
    'view'
  >;

  decryptForTxWithoutACP: TypedContractMethod<
    [ctHash: BigNumberish],
    [
      [boolean, string, bigint] & {
        allowed: boolean;
        error: string;
        decryptedValue: bigint;
      },
    ],
    'view'
  >;

  exists: TypedContractMethod<[], [boolean], 'view'>;

  initialize: TypedContractMethod<[_taskManager: AddressLike, _acl: AddressLike], [void], 'nonpayable'>;

  mockAcl: TypedContractMethod<[], [string], 'view'>;

  mockQueryDecrypt: TypedContractMethod<
    [ctHash: BigNumberish, arg1: BigNumberish, issuer: AddressLike],
    [[boolean, string, bigint] & { allowed: boolean; error: string }],
    'view'
  >;

  mockTaskManager: TypedContractMethod<[], [string], 'view'>;

  queryDecrypt: TypedContractMethod<
    [ctHash: BigNumberish, arg1: BigNumberish, acp: ACPStruct],
    [[boolean, string, bigint] & { allowed: boolean; error: string }],
    'view'
  >;

  querySealOutput: TypedContractMethod<
    [ctHash: BigNumberish, arg1: BigNumberish, acp: ACPStruct],
    [[boolean, string, string] & { allowed: boolean; error: string }],
    'view'
  >;

  seal: TypedContractMethod<[input: BigNumberish, key: BytesLike], [string], 'view'>;

  unseal: TypedContractMethod<[hashed: BytesLike, key: BytesLike], [bigint], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'decodeLowLevelReversion'): TypedContractMethod<[data: BytesLike], [string], 'view'>;
  getFunction(nameOrSignature: 'decryptForTxWithACP'): TypedContractMethod<
    [ctHash: BigNumberish, acp: ACPStruct],
    [
      [boolean, string, bigint] & {
        allowed: boolean;
        error: string;
        decryptedValue: bigint;
      },
    ],
    'view'
  >;
  getFunction(nameOrSignature: 'decryptForTxWithoutACP'): TypedContractMethod<
    [ctHash: BigNumberish],
    [
      [boolean, string, bigint] & {
        allowed: boolean;
        error: string;
        decryptedValue: bigint;
      },
    ],
    'view'
  >;
  getFunction(nameOrSignature: 'exists'): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'initialize'
  ): TypedContractMethod<[_taskManager: AddressLike, _acl: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'mockAcl'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'mockQueryDecrypt'
  ): TypedContractMethod<
    [ctHash: BigNumberish, arg1: BigNumberish, issuer: AddressLike],
    [[boolean, string, bigint] & { allowed: boolean; error: string }],
    'view'
  >;
  getFunction(nameOrSignature: 'mockTaskManager'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'queryDecrypt'
  ): TypedContractMethod<
    [ctHash: BigNumberish, arg1: BigNumberish, acp: ACPStruct],
    [[boolean, string, bigint] & { allowed: boolean; error: string }],
    'view'
  >;
  getFunction(
    nameOrSignature: 'querySealOutput'
  ): TypedContractMethod<
    [ctHash: BigNumberish, arg1: BigNumberish, acp: ACPStruct],
    [[boolean, string, string] & { allowed: boolean; error: string }],
    'view'
  >;
  getFunction(nameOrSignature: 'seal'): TypedContractMethod<[input: BigNumberish, key: BytesLike], [string], 'view'>;
  getFunction(nameOrSignature: 'unseal'): TypedContractMethod<[hashed: BytesLike, key: BytesLike], [bigint], 'view'>;

  filters: {};
}
