/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface MockCoFHEAddressBookInterface extends Interface {
  getFunction(nameOrSignature: 'exists' | 'getTm' | 'setTm' | 'unsetTm'): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: 'TaskManagerSet'): EventFragment;

  encodeFunctionData(functionFragment: 'exists', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getTm', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'setTm', values: [BigNumberish, AddressLike]): string;
  encodeFunctionData(functionFragment: 'unsetTm', values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getTm', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setTm', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unsetTm', data: BytesLike): Result;
}

export namespace TaskManagerSetEvent {
  export type InputTuple = [id: BigNumberish, previous: AddressLike, current: AddressLike];
  export type OutputTuple = [id: bigint, previous: string, current: string];
  export interface OutputObject {
    id: bigint;
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockCoFHEAddressBook extends BaseContract {
  connect(runner?: ContractRunner | null): MockCoFHEAddressBook;
  waitForDeployment(): Promise<this>;

  interface: MockCoFHEAddressBookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  exists: TypedContractMethod<[], [boolean], 'view'>;

  getTm: TypedContractMethod<[id: BigNumberish], [string], 'view'>;

  setTm: TypedContractMethod<[id: BigNumberish, tm: AddressLike], [void], 'nonpayable'>;

  unsetTm: TypedContractMethod<[id: BigNumberish], [void], 'nonpayable'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'exists'): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(nameOrSignature: 'getTm'): TypedContractMethod<[id: BigNumberish], [string], 'view'>;
  getFunction(nameOrSignature: 'setTm'): TypedContractMethod<[id: BigNumberish, tm: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'unsetTm'): TypedContractMethod<[id: BigNumberish], [void], 'nonpayable'>;

  getEvent(
    key: 'TaskManagerSet'
  ): TypedContractEvent<
    TaskManagerSetEvent.InputTuple,
    TaskManagerSetEvent.OutputTuple,
    TaskManagerSetEvent.OutputObject
  >;

  filters: {
    'TaskManagerSet(uint256,address,address)': TypedContractEvent<
      TaskManagerSetEvent.InputTuple,
      TaskManagerSetEvent.OutputTuple,
      TaskManagerSetEvent.OutputObject
    >;
    TaskManagerSet: TypedContractEvent<
      TaskManagerSetEvent.InputTuple,
      TaskManagerSetEvent.OutputTuple,
      TaskManagerSetEvent.OutputObject
    >;
  };
}
