/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export type InEuint32Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint32StructOutput = [ctHash: bigint, securityZone: bigint, utype: bigint, signature: string] & {
  ctHash: bigint;
  securityZone: bigint;
  utype: bigint;
  signature: string;
};

export interface TestBedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'addValue'
      | 'addValueTrivial'
      | 'getDecryptResultSafe'
      | 'getValue'
      | 'getValueHash'
      | 'publicValue'
      | 'publicValueHash'
      | 'publishDecryptResult'
      | 'setPublicValue'
      | 'setPublicValueTrivial'
      | 'setValue'
      | 'setValueTrivial'
      | 'storedValue'
      | 'storedValueHash'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'addValue', values: [InEuint32Struct]): string;
  encodeFunctionData(functionFragment: 'addValueTrivial', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'getDecryptResultSafe', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'getValue', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getValueHash', values?: undefined): string;
  encodeFunctionData(functionFragment: 'publicValue', values?: undefined): string;
  encodeFunctionData(functionFragment: 'publicValueHash', values?: undefined): string;
  encodeFunctionData(functionFragment: 'publishDecryptResult', values: [BytesLike, BigNumberish, BytesLike]): string;
  encodeFunctionData(functionFragment: 'setPublicValue', values: [InEuint32Struct]): string;
  encodeFunctionData(functionFragment: 'setPublicValueTrivial', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'setValue', values: [InEuint32Struct]): string;
  encodeFunctionData(functionFragment: 'setValueTrivial', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'storedValue', values?: undefined): string;
  encodeFunctionData(functionFragment: 'storedValueHash', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'addValue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addValueTrivial', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getDecryptResultSafe', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getValue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getValueHash', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'publicValue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'publicValueHash', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'publishDecryptResult', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setPublicValue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setPublicValueTrivial', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setValue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setValueTrivial', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'storedValue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'storedValueHash', data: BytesLike): Result;
}

export interface TestBed extends BaseContract {
  connect(runner?: ContractRunner | null): TestBed;
  waitForDeployment(): Promise<this>;

  interface: TestBedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  addValue: TypedContractMethod<[inValue: InEuint32Struct], [void], 'nonpayable'>;

  addValueTrivial: TypedContractMethod<[inValue: BigNumberish], [void], 'nonpayable'>;

  getDecryptResultSafe: TypedContractMethod<
    [input: BytesLike],
    [[bigint, boolean] & { value: bigint; decrypted: boolean }],
    'view'
  >;

  getValue: TypedContractMethod<[], [string], 'view'>;

  getValueHash: TypedContractMethod<[], [string], 'view'>;

  publicValue: TypedContractMethod<[], [string], 'view'>;

  publicValueHash: TypedContractMethod<[], [string], 'view'>;

  publishDecryptResult: TypedContractMethod<
    [input: BytesLike, result: BigNumberish, signature: BytesLike],
    [void],
    'nonpayable'
  >;

  setPublicValue: TypedContractMethod<[inValue: InEuint32Struct], [void], 'nonpayable'>;

  setPublicValueTrivial: TypedContractMethod<[inValue: BigNumberish], [void], 'nonpayable'>;

  setValue: TypedContractMethod<[inValue: InEuint32Struct], [void], 'nonpayable'>;

  setValueTrivial: TypedContractMethod<[inValue: BigNumberish], [void], 'nonpayable'>;

  storedValue: TypedContractMethod<[], [string], 'view'>;

  storedValueHash: TypedContractMethod<[], [string], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: 'addValue'): TypedContractMethod<[inValue: InEuint32Struct], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'addValueTrivial'): TypedContractMethod<[inValue: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'getDecryptResultSafe'
  ): TypedContractMethod<[input: BytesLike], [[bigint, boolean] & { value: bigint; decrypted: boolean }], 'view'>;
  getFunction(nameOrSignature: 'getValue'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'getValueHash'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'publicValue'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'publicValueHash'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'publishDecryptResult'
  ): TypedContractMethod<[input: BytesLike, result: BigNumberish, signature: BytesLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'setPublicValue'): TypedContractMethod<[inValue: InEuint32Struct], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setPublicValueTrivial'
  ): TypedContractMethod<[inValue: BigNumberish], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'setValue'): TypedContractMethod<[inValue: InEuint32Struct], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'setValueTrivial'): TypedContractMethod<[inValue: BigNumberish], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'storedValue'): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'storedValueHash'): TypedContractMethod<[], [string], 'view'>;

  filters: {};
}
