/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface TimestampBasedACPValidatorInterface extends Interface {
  getFunction(
    nameOrSignature: 'disabled' | 'revokeAllAt' | 'revokeAllExisting' | 'revokeSingle' | 'revokedSingle'
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: 'RevokedAll' | 'RevokedSingle'): EventFragment;

  encodeFunctionData(functionFragment: 'disabled', values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'revokeAllAt', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'revokeAllExisting', values?: undefined): string;
  encodeFunctionData(functionFragment: 'revokeSingle', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'revokedSingle', values: [AddressLike, BigNumberish]): string;

  decodeFunctionResult(functionFragment: 'disabled', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revokeAllAt', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revokeAllExisting', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revokeSingle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'revokedSingle', data: BytesLike): Result;
}

export namespace RevokedAllEvent {
  export type InputTuple = [issuer: AddressLike, at: BigNumberish];
  export type OutputTuple = [issuer: string, at: bigint];
  export interface OutputObject {
    issuer: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokedSingleEvent {
  export type InputTuple = [issuer: AddressLike, id: BigNumberish];
  export type OutputTuple = [issuer: string, id: bigint];
  export interface OutputObject {
    issuer: string;
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimestampBasedACPValidator extends BaseContract {
  connect(runner?: ContractRunner | null): TimestampBasedACPValidator;
  waitForDeployment(): Promise<this>;

  interface: TimestampBasedACPValidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  disabled: TypedContractMethod<[issuer: AddressLike, id: BigNumberish], [boolean], 'view'>;

  revokeAllAt: TypedContractMethod<[arg0: AddressLike], [bigint], 'view'>;

  revokeAllExisting: TypedContractMethod<[], [void], 'nonpayable'>;

  revokeSingle: TypedContractMethod<[id: BigNumberish], [void], 'nonpayable'>;

  revokedSingle: TypedContractMethod<[arg0: AddressLike, arg1: BigNumberish], [boolean], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'disabled'
  ): TypedContractMethod<[issuer: AddressLike, id: BigNumberish], [boolean], 'view'>;
  getFunction(nameOrSignature: 'revokeAllAt'): TypedContractMethod<[arg0: AddressLike], [bigint], 'view'>;
  getFunction(nameOrSignature: 'revokeAllExisting'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'revokeSingle'): TypedContractMethod<[id: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'revokedSingle'
  ): TypedContractMethod<[arg0: AddressLike, arg1: BigNumberish], [boolean], 'view'>;

  getEvent(
    key: 'RevokedAll'
  ): TypedContractEvent<RevokedAllEvent.InputTuple, RevokedAllEvent.OutputTuple, RevokedAllEvent.OutputObject>;
  getEvent(
    key: 'RevokedSingle'
  ): TypedContractEvent<RevokedSingleEvent.InputTuple, RevokedSingleEvent.OutputTuple, RevokedSingleEvent.OutputObject>;

  filters: {
    'RevokedAll(address,uint256)': TypedContractEvent<
      RevokedAllEvent.InputTuple,
      RevokedAllEvent.OutputTuple,
      RevokedAllEvent.OutputObject
    >;
    RevokedAll: TypedContractEvent<
      RevokedAllEvent.InputTuple,
      RevokedAllEvent.OutputTuple,
      RevokedAllEvent.OutputObject
    >;

    'RevokedSingle(address,uint256)': TypedContractEvent<
      RevokedSingleEvent.InputTuple,
      RevokedSingleEvent.OutputTuple,
      RevokedSingleEvent.OutputObject
    >;
    RevokedSingle: TypedContractEvent<
      RevokedSingleEvent.InputTuple,
      RevokedSingleEvent.OutputTuple,
      RevokedSingleEvent.OutputObject
    >;
  };
}
